### ISSUE TITLE
Inclusive language

### ISSUE THREAD

**Issue by andrewkantor** [linkedin/coral#14]
Can you address a couple of instances of language in the project where the wording can be made more inclusive? (example: whiltelist -> allowlist). We are trying to make the code in all LinkedIn projects more inclusive. Could you please examine whether or not these need to be updated, and make the changes? For suggested replacements see go/inclusivelanguage or google. THANK YOU!

Term | URL
-- | --
Blacklist | https://github.com/linkedin/coral/blob/b436653fe94c1b6bab30fcf7c9fd1869e2461afd/coral-spark/src/main/java/com/linkedin/coral/spark/UnsupportedHiveUDFsInSpark.java

**Comment by cwsteinbach** [comment]
Fixed in #15
