### ISSUE TITLE
Coral prepends hardcoded catalog name while translating a hive view to Presto

### ISSUE THREAD

**Issue by phd3** [linkedin/coral#18]
Coral hardcodes "hive" as the default catalog name while translating views to presto.

i.e. a view hql `SELECT a FROM test_schema.myview` translates to `SELECT a FROM hive.test_schema.myview` in Presto.

This is problematic for users who don't have "hive" as their default catalog name.

Presto Users reported this regression since coral was integrated for more complex hive view support: https://github.com/prestosql/presto/issues/5785

We need to modify the translation such that the underlying tables are resolved to the correct catalog name.

**Comment by phd3** [comment]
cc @HotSushi

**Comment by HotSushi** [comment]
Based on the discussion here: https://github.com/prestosql/presto/issues/5785?#issuecomment-721313566 , it makes sense to not prepend the catalog name in coral-presto. This is also the behavior for other modules like coral-spark.
