### ISSUE TITLE
Support for other Hive versions

### ISSUE THREAD

**Issue by jongn** [linkedin/coral#197]
Currently Coral is using Hive 1.0, would there be any plans to support other Hive versions?

This is causing issues with systems using Hive 2.1.0 and above, for example: several date functions such as date_add had their function signatures changed in 2.1.0 release. Reference: https://cwiki.apache.org/confluence/display/hive/languagemanual+udf

**Comment by ljfgem** [comment]
Hi @jongn, IIRC, all the data functions (like `to_date`, `date_add`) are returning `date` type in Coral, so it is aligned with Hive 2.1.0.
We added some configs for LinkedIn's internal Hive 1.0 use in https://github.com/linkedin/coral/blob/7083f94f3c2315b4b026c97c9bc05b69135a31f7/coral-trino/src/main/java/com/linkedin/coral/trino/rel2trino/CoralTrinoConfigKeys.java

**Comment by jongn** [comment]
Thanks! That's a nice addition.
