### ISSUE TITLE
Shade trino-parser dependency of coral-trino

### ISSUE THREAD

**Issue by joshthoward** [linkedin/coral#205]
When bumping the Coral dependency version in Trino, we noticed that `coral-trino` has a new dependency on `trino-parser`.

One of our maintainers brought up the fact that the `trino-parser` is not designed to be depended on by other projects i.e. not guaranteed to maintain backward compatibility. In order to preempt future incompatibilities, would the folks in Coral consider shading the `trino-parser` dependency?

For reference, the conversation is [here](https://github.com/trinodb/trino/pull/10226).

**Comment by wmoustafa** [comment]
Added a comment in the Trino PR referenced above.

**Comment by joshthoward** [comment]
@shenodaguirguis Do you have an expectation for when you will be able to shade the dependency?

**Comment by shenodaguirguis** [comment]
@joshthoward thanks for checking, I will work on this next week. Will share the PR here once ready

**Comment by joshthoward** [comment]
@shenodaguirguis That works. Thanks again for looking into this.

**Comment by shenodaguirguis** [comment]
We changed trino-parser dependency to compileOnly/Implementation in https://github.com/linkedin/coral/pull/222
