### ISSUE TITLE
Support translation of function greatest(<NUMERIC>, <NUMERIC>) in Presto

### ISSUE THREAD

**Issue by JamesRTaylor** [linkedin/coral#30]
Many of our Hive view queries are failing to execute in Presto based on lack of support for the function greatest(&lt;NUMERIC&gt;, &lt;NUMERIC&gt;). Would it be possible to add support for this? We're currently using prestosql 346 which uses Coral 1.0.12.

**Comment by kxu1026** [comment]
Hi, James, we will add the support. thanks for your comment.

**Comment by JamesRTaylor** [comment]
Turns out we're hitting this issue in Trino: https://github.com/trinodb/trino/issues/6370. We've had to disable Coral for now until this is fixed. Unfortunately the user experience out-of-the-gate was not a good one. If we see demand for this feature again, I'll pass along any blockers. One particular area (which is likely tricky) is supporting the geospatial built-in functions in a consistent manner.

**Comment by wmoustafa** [comment]
More details on Trino's translation of views from `information_schema` and the exception in https://github.com/trinodb/trino/issues/6370 can be found in https://github.com/trinodb/trino/pull/6374. Hopefully that can be committed soon.

@JamesRTaylor once https://github.com/trinodb/trino/issues/6370 is committed, would help to add support to greatest?

Could you please elaborate on what you meant by `supporting the geospatial built-in functions in a consistent manner`? Is geospatial function support needed just as part of querying views in `information_schema` or in general?

**Comment by JamesRTaylor** [comment]
> would it still be helpful to add support to greatest?

Once the Trino issue is fixed, I suspect supporting `greatest` won't be a high priority. I think supporting `current_date` and `current_timestamp` will be important. Also consistent behavior of all other date/time built-ins will be important: https://trino.io/docs/current/functions/datetime.html

> Could you please elaborate on what you meant by supporting the geospatial built-in functions in a consistent manner?

Supporting all these functions consistently between Hive and Presto: https://trino.io/docs/current/functions/geospatial.html

**Comment by wmoustafa** [comment]
@JamesRTaylor Have you considered [Transport](https://github.com/linkedin/transport) for that?

**Comment by JamesRTaylor** [comment]
Didn't know about Transport, but kind of assumed that Coral would leverage something like that under-the-hood. If every org has to use Transport themselves for standard built-in functions, that seems like it'd greatly reduce the purpose of Coral, no?

**Comment by wmoustafa** [comment]
At a high-level, yes Coral utilizes Transport under the hood, but also Coral has two types of automatic UDF rewrites: built-in functions and user-defined functions (UDFs). Built-in function rewrite takes care of functions available in source and target engines (e.g., rewriting `INSTR` in Hive to `STRPOS` in Trino/Presto). On the other hand, UDF (non-built-in) rewrite leverages Transport mapping between UDFs written in Transport's API when the functions are not normally available (or rewritable) as built-in functions in both engines. I think geo-spatial functions fall in this category. For example, one could write `ST_Intersects` in Transport's API, and Transport will produce Hive, Presto, and Spark versions of this UDF; then Coral can pick the correct variant of the UDF depending on where it runs.

**Comment by JamesRTaylor** [comment]
Many of the geospatial built-ins are standard, in particular the ones prefixed with `ST_` (there's even a spec around them). I'd put that in the former category that should ideally be covered by Coral. Others less so, and the approach you mentioned makes sense. But thanks for letting me know about Transport. Very cool technology.

**Comment by ljfgem** [comment]
Closing it as #153 has been merged.
