### ISSUE TITLE
Discussion channel

### ISSUE THREAD

**Issue by djKooks** [linkedin/coral#42]
Hello,
Sorry for leaving message here, but I couldn't find place to ask about good usage(or example) of this project.

Is there some kind of opened discussion channel(gitter, discord...)?
There are Slack link, but seems this is not opened.

Thanks.

**Comment by wmoustafa** [comment]
Thanks for pointing this out. I have opened https://github.com/linkedin/coral/pull/43 to update the link while we streamline the invitation process. I am also sharing the link [here](https://join.slack.com/t/coral-sql/shared_invite/zt-krbxjj9w-YkIWKVAufVtlHyoKtU6DWQ) for convenience.

For how to use the project, a good starting place is the unit tests of the various modules. Further, it is already integrated with [Trino](https://github.com/trinodb) (formerly Presto SQL) for translating HiveQL to Presto SQL. Integration with Spark uses the coral-spark module, but also requires small patches to the Spark engine.

**Comment by djKooks** [comment]
@wmoustafa thank you~
