### ISSUE TITLE
connect hms(hive metastore store) sometimes breaks and does not reconnect

### ISSUE THREAD

**Issue by KANLON** [linkedin/coral#479]
when running the project ，after a period of time, connect hms sometimes breaks and does not reconnect (It may be a network issue, etc)

bug it not reconnect, I think this is a bit problematic

when i read code，i find  it `use new HiveMetaStoreClient(conf)`   to create IMetaStoreClient  in MetastoreProvider#getRemoteMetastoreClient method . This way is not will reconnect, it should be replace `RetryingMetaStoreClient.getProxy(conf)`

some error message like
```
org.apache.thrift.transport.TTransportException Create breakpoint java.net.SocketException:Connection reset by peer:socket write error
at org.apache.thrift.transport.TIOStreamTransport.flush(TIOStreamTransport.java:161)~[libthrift-0.9.2.jar:0.9.2]
```

**Comment by 1fanwang** [comment]
Closed by https://github.com/linkedin/coral/pull/480, thank you for the contribution @KANLON
