### ISSUE TITLE
Support for LATERAL VIEW json_tuple

### ISSUE THREAD

**Issue by wendigo** [linkedin/coral#53]
Currently Coral lacks support of the `LATERAL VIEW json_tuple` which is a Hive syntax leveraging `json_tuple` UDTF. 

The main difference between `json_tuple` and other UDTFs like `explode` is that `json_tuple` is column generating function (in contrast to `explode` which is a row generating function).

`json_tuple` has following signature in Hive: 

```
json_tuple(string jsonStr,string k1,...,string kn)
```

Where `jsonStr` is a string or column reference (of string type) holding serialized JSON object. `k1, ..., kn` are field names that are being extracted from `jsonStr` JSON object. So having `jsonStr`:

```
{"user_id": 1000, "name": "Mateusz", "surname": "Gajewski"}
```

`SELECT json_tuple(jsonStr, "name", "surname", "user_id")`

will return a tuple (this Hive concept is weird tbh):

```
"1000", "Mateusz", "Gajewski"
```

and by default, those columns are having automatically generated names (`c0`, `c1`,...).

Hive allows to name those columns which Coral doesn't handle as well:

```
SELECT json_tuple(jsonStr, "name", "surname", "user_id") as (name, surname, user_id)
```

And finally:

Hive's:

```
SELECT v.col, v.col2 FROM json_test t 
  LATERAL VIEW json_tuple(t.col, 'field', 'field2') v as col, col2
```

should be translated to Trino's/Presto's query (or similar shape):

```
SELECT v.field AS col, v.field2 AS col2 from json_test t 
  CROSS JOIN LATERAL (
    SELECT cast(json_parse(t.col) as ROW(field varchar, field2 varchar)) as v
  );
```

Please note that due to Hive's `AS` clause it's possible to extract `field` from JSON as column `col`.

**Comment by findepi** [comment]
I noted some thoughts over there: https://github.com/trinodb/trino/issues/7242#issuecomment-795685037
